### ISSUE TITLE
HA Automation snippet for " Create a Send Message Automation" might be outdated

### ISSUE THREAD

**Issue by t984447** [meshtastic/Meshtastic#1252]
###  Automatiation for message via MQTT might be outdated 
[MQTT: Home Assistant Integrations for Meshtastic](https://meshtastic.org/docs/software/integrations/mqtt/home-assistant/)
Topic: Create a Send Message Entity
Sub-topic: Create a Send Message Automation

Home Automation OS Versions
- **Core**
2024.5.2
- **Supervisor**
2024.05.1
- **Operating System**
12.3
- **Frontend**
20240501.1

### Describe what section of the docs is outdated or otherwise in need of change
This guide gives an example at the bottom which ends with Home Assistant Automatiation YAML Editor
giving following error when trying to save;
`Message malformed: extra keys not allowed @ data['0']`
![Meshtastic_Automation_guide_error](https://github.com/meshtastic/meshtastic/assets/10352285/a3531a11-3773-4675-ab88-35727607197b)

### Suggested Changes
Please note that I am currently very fresh on both Home Assistant and Meshtastic. There might be better errors.
The changes I made is;
- Delay definitions is no longer split (hours, minutes, seconds) but rather defined in one HH:MM:SS input; e.g 2 Seconds = "00:00:02"
- YAML positioning re-format brining Trigger and Action to the same level as Alias.

My code which I got working with added Replace me changes;
[REPLACE ME with full topic path]
[REPLACE ME with node ID]

```
alias: Meshtastic - Send Automation
description: Create a Send Message Automation
trigger:
  - platform: state
    entity_id:
      - input_text.meshtastic_send_box
action:
  - delay: "00:00:02"
  - service: mqtt.publish
    data:
      qos: 0
      retain: false
      topic: [REPLACE ME with full topic path]
      payload: >-
        {"from":[REPLACE ME with node ID],"type":"sendtext","payload":"{{    
        states('input_text.meshtastic_send_box') }}"}
  - delay: "00:00:01"
  - service: input_text.set_value
    data:
      value: " "
    target:
      entity_id: input_text.meshtastic_send_box
  - delay: "00:00:02"
mode: single

```
