### ISSUE TITLE
[Documentation Change Request]: Add channel to MQTT messsage sending in Home Assistant

### ISSUE THREAD

**Issue by todd2982** [meshtastic/meshtastic#1603]
### Request Details

This is in addition to the current issue #1252 to update the current documentation.  Currently it has format errors that are not accepted by Home Assistant, and the message sending via MQTT fails as the current example is written.

The payload statement in the example automation at https://meshtastic.org/docs/software/integrations/mqtt/home-assistant/#create-a-send-message-automation should include the channel to be used for the message.  For most users this will be channel 0, but could be any of the available channel index numbers.  It should be an index referencing a channel that is on both the sending and receiving device. 

```YAML
alias: Mesh - Send message via send box
description: ""
triggers:
  - entity_id:
      - input_text.meshtastic_send_box
    trigger: state
conditions: []
actions:
  - delay:
      hours: 0
      minutes: 0
      seconds: 1
      milliseconds: 0
  - data:
      topic: msh/US/2/json/mqtt/!67ea9400
      payload: >-
        {"channel":0,"from":1743426560,"type":"sendtext","payload":"{{
        states('input_text.meshtastic_send_box') }}"}
    action: mqtt.publish
  - delay:
      hours: 0
      minutes: 0
      seconds: 1
      milliseconds: 0
  - target:
      entity_id: input_text.meshtastic_send_box
    data:
      value: " "
    action: input_text.set_value
  - delay:
      hours: 0
      minutes: 0
      seconds: 2
      milliseconds: 0
mode: single

```

The used AI to troubleshoot the above example for my system, and testing will need to be done by others to validate.

Testing environment:
Home Assistant: 2024.11.3
MQTT server: Private
Sending radio: Heltec V3 running 2.5.9 using private channel index 2
Receiving radio: Seedcard T1000-e running 2.5.14 using private channel index 2
OK to MQTT enabled at each end
Sending node is using JSON option in MQTT settings

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
